M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date 23.06.2025 (пн) 15:00:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-23T15:00:54+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X3.46Y6.975
X9.24Y6.975
X16.16Y6.975
X21.94Y6.975
T2
X8.89Y24.13
X16.51Y24.13
T0
M30
